@startuml

top to bottom direction
skinparam linetype ortho

class MusicManagerUI {
  + MusicManagerUI(LoginObserver, User): 
  + songService: SongServiceImpl
  + songs: List<Song>
  + user: User
  + selectedSong: Optional<Song>
  + songTable: JTable
  + linkGeneratorService: YTLinkGeneratorServiceImpl
  + loginObserver: LoginObserver
  + triggerLogout(): void
  + onUpdateSongList(List<Song>): void
  + newSong(): void
  + deleteSong(): void
  + setupUI(): void
  + playSong(): void
  + editSong(): void
}
interface SongListObserver << interface >> {
  + onUpdateSongList(List<Song>): void
}
class SongServiceImpl {
  + SongServiceImpl(User, SongRepository, SongListObserver): 
  + user: User
  + songListObserver: SongListObserver
  + songRepository: SongRepository
  + create(Song): void
  + delete(Song): void
  + getAllSongsForUser(): List<Song>
  + update(Song): void
  + searchSongsByTitle(String): List<Song>
}

MusicManagerUI    -[#008200,dashed]-^  SongListObserver 
MusicManagerUI    -[#595959,dashed]->  SongServiceImpl  : "«create»"
MusicManagerUI   "1" *-[#595959,plain]-> "songService\n1" SongServiceImpl  
SongServiceImpl  "1" *-[#595959,plain]-> "songListObserver\n1" SongListObserver 
@enduml
