@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class MusicManagerUI {
  + MusicManagerUI(LoginObserver, User): 
  + songService: SongServiceImpl
  + songs: List<Song>
  + user: User
  + selectedSong: Optional<Song>
  + songTable: JTable
  + linkGeneratorService: YTLinkGeneratorServiceImpl
  + loginObserver: LoginObserver
  + triggerLogout(): void
  + onRefresh(List<Song>): void
  + newSong(): void
  + deleteSong(): void
  + setupUI(): void
  + playSong(): void
  + editSong(): void
}
interface SongListObserver << interface >> {
  + onRefresh(List<Song>): void
}

MusicManagerUI    -[#008200,dashed]-^  SongListObserver 
@enduml
