name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Build and test project with Maven
        run: mvn package --file pom.xml --batch-mode --update-snapshots --no-transfer-progress

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./mm-report/target/site/jacoco-aggregate/
          files: jacoco.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true