name: CI

on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - 0-mm-utils/**
      - 1-mm-domain/**
      - 2-mm-application/**
      - 3-mm-plugin/**
      - mm-report/**
      - pom.xml
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=marcauberer_music-manager

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./mm-report/target/site/jacoco-aggregate/
          files: jacoco.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: music-manager.jar
          path: 3-mm-plugin/target/*-jar-with-dependencies.jar